// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNS.Models;

#nullable disable

namespace QLNS.Migrations
{
    [DbContext(typeof(QuanlynhansuDbContext))]
    [Migration("20240430152801_csdl")]
    partial class csdl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNS.Models.BangCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaBangCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBangCap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("BangCap", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ChucVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LuongCoBan")
                        .HasColumnType("int");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ChuyenMon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyenMon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("ChuyenMon", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.CongTac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BangCapID")
                        .HasColumnType("int");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiemCongTac")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaCongTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDich")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BangCapID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("CongTac", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.DanToc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaDanToc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanToc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("DanToc", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.HopDong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<string>("TenHopDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.KhenThuong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LyDoKhenThuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaKhenThuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TienThuong")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("KhenThuong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.KhoanTru", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LyDoKhoanTru")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaKhoanTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SoTienKhoanTru")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("KhoanTru", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<int>("KhenThuongID")
                        .HasColumnType("int");

                    b.Property<int>("KhoanTruID")
                        .HasColumnType("int");

                    b.Property<int>("LuongCoBanID")
                        .HasColumnType("int");

                    b.Property<string>("LyDoKhenThuongID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoKhoanTruID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("PhuCapID")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenPhuCapID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThangID")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianLamViecID")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrangLuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("TongThuNhap")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("KhenThuongID");

                    b.HasIndex("KhoanTruID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("PhuCapID");

                    b.HasIndex("ThoiGianLamViecID");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.NghiPhep", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LyDoNghi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayNghi")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("NghiPhep", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.NguoiDung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChiID")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("SDTID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BangCapID")
                        .HasColumnType("int");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<int>("ChuyenMonID")
                        .HasColumnType("int");

                    b.Property<int>("DanTocID")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapCanCuoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCapCanCuoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int>("QuocTichID")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TonGiaoID")
                        .HasColumnType("int");

                    b.Property<int>("TrinhDoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BangCapID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("ChuyenMonID");

                    b.HasIndex("DanTocID");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("QuocTichID");

                    b.HasIndex("TonGiaoID");

                    b.HasIndex("TrinhDoID");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.PhuCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaPhuCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SoTienPhuCap")
                        .HasColumnType("real");

                    b.Property<string>("TenPhuCap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("PhuCap", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.QuocTich", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaQuocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuocTich")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("QuocTich", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ThoiGianLamViec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("NghiPhepID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayCong")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayNghiID")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NghiPhepID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThoiGianLamViec", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ThongKeNam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ThangID")
                        .HasColumnType("int");

                    b.Property<float>("TongDoanhThuNam")
                        .HasColumnType("real");

                    b.Property<float>("TongDoanhThuThangID")
                        .HasColumnType("real");

                    b.Property<int>("namID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ThongKeNam", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ThongKeThang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<float>("ThucLanh")
                        .HasColumnType("real");

                    b.Property<float>("TongDoanhThuThang")
                        .HasColumnType("real");

                    b.Property<int>("nam")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ThongKeThang", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.TonGiao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaTonGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTonGiao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("TonGiao", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.TrinhDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaTrinhDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrinhDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("TrinhDo", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.CongTac", b =>
                {
                    b.HasOne("QLNS.Models.BangCap", null)
                        .WithMany("CongTac")
                        .HasForeignKey("BangCapID");

                    b.HasOne("QLNS.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.NhanVien", "NhanVien")
                        .WithMany("CongTac")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.HopDong", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.HasOne("QLNS.Models.ChucVu", "ChucVu")
                        .WithMany("Luong")
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.KhenThuong", "KhenThuong")
                        .WithMany("Luong")
                        .HasForeignKey("KhenThuongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.KhoanTru", "KhoanTru")
                        .WithMany("Luong")
                        .HasForeignKey("KhoanTruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.NhanVien", "NhanVien")
                        .WithMany("Luong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.PhuCap", "PhuCap")
                        .WithMany("Luong")
                        .HasForeignKey("PhuCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.ThoiGianLamViec", "ThoiGianLamViec")
                        .WithMany("Luong")
                        .HasForeignKey("ThoiGianLamViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("KhenThuong");

                    b.Navigation("KhoanTru");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuCap");

                    b.Navigation("ThoiGianLamViec");
                });

            modelBuilder.Entity("QLNS.Models.NghiPhep", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "NhanVien")
                        .WithMany("NghiPhep")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.NguoiDung", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "NhanVien")
                        .WithMany("NguoiDung")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.HasOne("QLNS.Models.BangCap", "BangCap")
                        .WithMany("NhanVien")
                        .HasForeignKey("BangCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.ChucVu", "ChucVu")
                        .WithMany("NhanVien")
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.ChuyenMon", "ChuyenMon")
                        .WithMany("NhanVien")
                        .HasForeignKey("ChuyenMonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.DanToc", "DanToc")
                        .WithMany("NhanVien")
                        .HasForeignKey("DanTocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.PhongBan", "PhongBan")
                        .WithMany("NhanVien")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.QuocTich", "QuocTich")
                        .WithMany("NhanVien")
                        .HasForeignKey("QuocTichID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.TonGiao", "TonGiao")
                        .WithMany("NhanVien")
                        .HasForeignKey("TonGiaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNS.Models.TrinhDo", "TrinhDo")
                        .WithMany("NhanVien")
                        .HasForeignKey("TrinhDoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangCap");

                    b.Navigation("ChucVu");

                    b.Navigation("ChuyenMon");

                    b.Navigation("DanToc");

                    b.Navigation("PhongBan");

                    b.Navigation("QuocTich");

                    b.Navigation("TonGiao");

                    b.Navigation("TrinhDo");
                });

            modelBuilder.Entity("QLNS.Models.ThoiGianLamViec", b =>
                {
                    b.HasOne("QLNS.Models.NghiPhep", "NghiPhep")
                        .WithMany("ThoiGianLamViec")
                        .HasForeignKey("NghiPhepID");

                    b.HasOne("QLNS.Models.NhanVien", "NhanVien")
                        .WithMany("ThoiGianLamViec")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NghiPhep");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.BangCap", b =>
                {
                    b.Navigation("CongTac");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.ChucVu", b =>
                {
                    b.Navigation("Luong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.ChuyenMon", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.DanToc", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.KhenThuong", b =>
                {
                    b.Navigation("Luong");
                });

            modelBuilder.Entity("QLNS.Models.KhoanTru", b =>
                {
                    b.Navigation("Luong");
                });

            modelBuilder.Entity("QLNS.Models.NghiPhep", b =>
                {
                    b.Navigation("ThoiGianLamViec");
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.Navigation("CongTac");

                    b.Navigation("Luong");

                    b.Navigation("NghiPhep");

                    b.Navigation("NguoiDung");

                    b.Navigation("ThoiGianLamViec");
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.PhuCap", b =>
                {
                    b.Navigation("Luong");
                });

            modelBuilder.Entity("QLNS.Models.QuocTich", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.ThoiGianLamViec", b =>
                {
                    b.Navigation("Luong");
                });

            modelBuilder.Entity("QLNS.Models.TonGiao", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.TrinhDo", b =>
                {
                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
